# Generated by Django 3.1 on 2021-02-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlist_bid_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='img',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
