# Generated by Django 3.1 on 2021-02-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210228_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='comentario',
            field=models.ManyToManyField(default='', related_name='Comment', to='auctions.Comment'),
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='monto',
            field=models.ManyToManyField(related_name='Amount', to='auctions.Bid'),
        ),
    ]
