# Generated by Django 3.1 on 2021-02-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210228_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlist',
            name='monto',
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='montoinicial',
            field=models.IntegerField(default=0),
        ),
    ]
