# Generated by Django 3.1 on 2021-02-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210228_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='categoria',
            field=models.CharField(default='', max_length=64),
        ),
    ]
