# Generated by Django 3.1 on 2021-03-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_auctionlist_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='img',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
