# Generated by Django 3.1 on 2021-03-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210301_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, default='', related_name='watchList', to='auctions.AuctionList'),
        ),
    ]
