# Generated by Django 3.1 on 2021-03-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_user_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='auctionlist',
            name='user',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
