# Generated by Django 3.1 on 2021-03-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210303_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
